// Package tools binds the MCP tools to the lifecycle operations for one
// `orca mcp` process.
package tools

import (
	"context"
	"encoding/json"
	"errors"
	"maps"
	"slices"
	"strings"
	"sync"
	"time"

	"github.com/alex2481kobe/orca/internal/config"
	"github.com/alex2481kobe/orca/internal/lifecycle"
	"github.com/alex2481kobe/orca/internal/mcp"
	"github.com/alex2481kobe/orca/internal/run"
	"github.com/alex2481kobe/orca/internal/worker"
)

// sweepEvery throttles the opportunistic retention sweep.
const sweepEvery = 10 * time.Minute

// Handler serves tools/call for one `orca mcp` process. It is safe for
// concurrent calls.
type Handler struct {
	d          lifecycle.Deps
	instanceID string

	// Seams; production uses time.Now and lifecycle.Sweep.
	now   func() time.Time
	sweep func(lifecycle.Deps) error

	mu        sync.Mutex
	lastSweep time.Time // zero until the first sweep starts
}

// New returns the MCP handler for one `orca mcp` process. instanceID is the
// fallback caller id for this process (a random id generated by cmd/orca).
func New(d lifecycle.Deps, instanceID string) *Handler {
	return &Handler{d: d, instanceID: instanceID, now: time.Now, sweep: lifecycle.Sweep}
}

// Tools is the tools/list payload, rendered from the adapters' Facts.
func (h *Handler) Tools() []mcp.Tool { return mcp.Tools(Facts(h.d.Adapters)) }

// Facts returns every adapter's Facts, by name.
func Facts(adapters map[string]worker.Adapter) []worker.Facts {
	var out []worker.Facts
	for _, n := range slices.Sorted(maps.Keys(adapters)) {
		out = append(out, adapters[n].Facts())
	}
	return out
}

// Call runs one tool. Identity is resolved per call: under Codex it comes
// from this call's _meta. Every error returned is a *run.Error.
func (h *Handler) Call(ctx context.Context, name string, args, meta json.RawMessage, client mcp.ClientInfo) (any, error) {
	id, source := config.ResolveCaller(h.d.Env, client.Name, meta, h.instanceID)
	c := lifecycle.Caller{ID: id, Source: run.CallerSource(source)}
	out, err := h.dispatch(ctx, c, name, args)
	if err != nil {
		return nil, h.toolError(err)
	}
	return out, nil
}

func (h *Handler) dispatch(ctx context.Context, c lifecycle.Caller, name string, args json.RawMessage) (any, error) {
	switch name {
	case "run":
		defer h.maybeSweep()
		return h.run(c, args)
	case "send":
		defer h.maybeSweep()
		return h.send(c, args)
	case "wait":
		return h.wait(ctx, args)
	case "result":
		return h.result(args)
	case "status":
		return h.status(args)
	case "stop":
		return h.stop(args)
	}
	return nil, run.Errorf(run.CodeInvalidInput, "unknown tool %q", name)
}

func summaries(runs []*run.Run) []mcp.RunSummary {
	out := make([]mcp.RunSummary, len(runs))
	for i, r := range runs {
		out[i] = mcp.Summarize(r)
	}
	return out
}

// maybeSweep starts a retention sweep at most once per sweepEvery. It never
// blocks the reply, and its error is ignored: the next sweep tries again.
func (h *Handler) maybeSweep() {
	now := h.now()
	h.mu.Lock()
	due := h.lastSweep.IsZero() || now.Sub(h.lastSweep) >= sweepEvery
	if due {
		h.lastSweep = now
	}
	h.mu.Unlock()
	if due {
		go func() { _ = h.sweep(h.d) }()
	}
}

// toolError makes err something the model sees. A *run.Error or run.Code
// anywhere in the chain keeps its code, and so does any error that matches
// STORE_IO (a failed publication), so a wrapped STORE_IO stays STORE_IO;
// anything else is PROTOCOL. The state dir is shortened to keep messages
// short.
func (h *Handler) toolError(err error) *run.Error {
	var (
		re   *run.Error
		code run.Code
	)
	out := &run.Error{Code: run.CodeProtocol, Message: err.Error()}
	switch {
	case errors.As(err, &re):
		out.Code = re.Code
		if err == error(re) {
			out.Message = re.Message
		}
	case errors.As(err, &code):
		out.Code = code
	case errors.Is(err, run.CodeStoreIO):
		out.Code = run.CodeStoreIO
	}
	if h.d.StateHome != "" {
		out.Message = strings.ReplaceAll(out.Message, h.d.StateHome, "$ORCA_HOME")
	}
	return out
}
